name: GetManager
permissions:
  contents: write
  actions: read

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: true
        type: string

jobs:
  get_ksu_manager:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y git curl jq

      - name: 设定 KSU 环境变量
        run: |
          echo "This is the SukiSU variant"
          git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra.git
          cd SukiSU-Ultra
          KSU_GIT_VERSION=$(git rev-list --count HEAD)
          KSU_VERSION=$((10000 + KSU_GIT_VERSION + 700))
          echo $KSU_VERSION
          echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV

      - name: 获取 Spoofed-Manager
        run: |
          echo "SukiSU..."
          REPO="SukiSU-Ultra/SukiSU-Ultra"
          FILENAME="build-manager.yml"

          # 获取最新成功构建
          BUILD_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO/actions/workflows/$FILENAME/runs?status=success" | \
          jq -r '.workflow_runs[0].id')
          echo "BUILD_ID=$BUILD_ID"

          # 获取 artifacts
          ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO/actions/runs/$BUILD_ID/artifacts")

          # 只拿 Spoofed-Manager
          DOWNLOAD_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name == "Spoofed-Manager") | .archive_download_url')
          echo "DOWNLOAD_URL=$DOWNLOAD_URL"

          # 下载
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o "${{ inputs.kernelsu_variant }}-Spoofed-管理器(${{ env.KSU_VERSION }}).zip" "$DOWNLOAD_URL"
          unzip *.zip

      - name: 上传编译资产
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.kernelsu_variant }}-Spoofed-Manager(${{ env.KSU_VERSION }})
          path: |
            *.apk
